### ISSUE TITLE
sb-pets does not hatch all kinds of eggs

### ISSUE THREAD

**Issue by therealmaxmoon** [DC23/scriptabit#26]
- scriptabit version 1.16.0

`sb-pets --hatch-pets` says: 

> "Hatched 0 new pets"

But there are hatchable eggs in the inventory, like rooster, spider, tyrannosaur and whale eggs. Maybe those are just too new.

**Comment by therealmaxmoon** [comment]
Found something useful here: https://scriptabit.readthedocs.io/en/latest/usage/petcare.html

The following command will hatch all kind of eggs:
`sb-pets --hatch-pets --quest-pets`

**Comment by DC23** [comment]
Yes. The base pets are on by default, you can turn them off with `--no-base-pets`. The extra quest pets are off by default, and they can be turned on with `--quest-pets`.  There is also a `--magic-pets` flag for the other special pets.

The same flags work for both hatching and feeding. I need to update the code though, since I don't currently have handling for a couple of the newest pet types. I might see if I can rethink my implementation so I don't need to manually update the pets. The only problem is knowing which pets have a preferred food and which ones eat anything (mostly just the magic pets).

Also, I don't think the new purple potion is supported yet either.

**Comment by therealmaxmoon** [comment]
Thanks a lot for the explanation. So the correct command to hatch all kind of eggs would be:
`sb-pets --hatch-pets --quest-pets --magic-pets`

**Comment by DC23** [comment]
That looks right.
